spring:
    jpa:
        hibernate:
            ddl-auto: none
        database-platform: h2
    sql:
        init:
            platform: h2
            mode: embedded
    datasource:
        url: jdbc:h2:~/civediamodomani
        username: sa
        password:
        driver-class-name: org.h2.Driver
