spring:
    mail:
        protocol: smtp
        host: smtp.office365.com
        port: 587
        username: devtestiet@outlook.it
        password: devtesting22
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enabled: true
                        required: true
    jpa:
        show-sql: false
        properties:
            hibernate.format_sql: false
    servlet:
        multipart:
            max-file-size: 20MB
            max-request-size: 20MB
    application:
        name: Ci Vediamo Domani
    h2:
        console:
            path: /h2
            enabled: true
    profiles:
        active: dev
server:
    port: 8095
logging:
    level:
        org.springframework.security: debug
